### ISSUE TITLE
Error: No "InstagramAPI" in settings.

### ISSUE THREAD

**Issue by mario589736** [krstffr/meteor-instagram-fetcher#12]
Hey, 

i put this one into my settings.json in my projects root directory:

```
{
"InstagramAPI": {
    "CLIENT_ID": "xxx",
    "CLIENT_SECRET": "xxx"
  }
}
```

for sure i put my id and secret.

i get this error:

```
"/Users/hansihinterseer/.meteor/packages/meteor-tool/.1.1.10.vpl64b++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:245 throw(ex); ^
Error: No "InstagramAPI" in settings.
at packages/krstffr_instagram-fetcher/instagram-fetcher.js:228:1
at /Users/hansihinterseer/test/.meteor/local/build/programs/server/boot.js:249:5"

```
any ideas?

Mario

**Comment by mozky** [comment]
Be sure to tell meteor where your settings.json is located, try this:
`meteor --settings settings.json`

**Comment by mario589736** [comment]
Thats it, i had it here ./../settings.json. Thanks!

**Comment by krstffr** [comment]
I added a note about this to the readme. Thanks!
